services:
  devcontainer:
    container_name: devcontainer-langchain-chat-demo
    image: arleth-python
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      OLLAMA_HOST: http://host.docker.internal:11434
    volumes:
      - .:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: